<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GetGuidec.aspx.cs" Inherits="AdvAli.Web.website.GetGuidec" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title></title>
</head>
<body>
<script type="text/javascript">
var objid = "swtf";
function $(id) { return document.getElementById(id); }
//页面加载成功
if (window.addEventListener) { window.addEventListener("scroll", scrollHandler, false); } else if (window.attachEvent) { window.attachEvent("onscroll", scrollHandler); } else { window.onscroll = scrollHandler; }
function scrollHandler() {var msgboxs = document.getElementById(objid);if (msgboxs)if ((document.documentElement) && (document.documentElement.clientHeight)) {msgboxs.style.top = document.documentElement.scrollTop + (document.documentElement.clientHeight - msgboxsHeight) - 10 + "px";}else if (document.body.clientHeight) {msgboxs.style.top = document.body.scrollTop + (document.body.clientHeight - msgboxsHeight) - 10 + "px";}else {msgboxs.style.top = window.scrollTop + (window.clientHeight - msgboxsHeight) - 10 + "px";}}
function Count(){var scripts = document.createElement("script");scripts.type="text/javascript";var pageurl = escape(location.href);var pagetitle = escape(document.title);var referrer = escape(document.referrer);scripts.src="<%=WebSiteUrl%>/script/count.aspx?siteid=<%=siteId%>&getsiteid=<%=getSiteId%>&pageurl="+pageurl+"&pagetitle="+pagetitle+"&referrer="+referrer;document.body.insertBefore(scripts, document.body.childNodes[0]);}
function add_css(the_css) { var the_style = document.createElement('style'); document.getElementsByTagName('head')[0].appendChild(the_style); try { the_style.innerHTML = the_css; } catch (e) { var parts = the_css.split(/\s*[{}]\s*/); for (var i = 0; i < parts.length; i += 2) the_style.styleSheet.addRule(parts[i], parts[i + 1]); } }
add_css("#swtm {background:url(../images/bm.jpg) no-repeat;width:419px;height:224px;position:absolute;z-index:999;right:5px;font-family:Arial,宋体;font-size:12px;}#swtm div.msgbox_title {font-size:14px;font-weight:bold;color:White;float:left;line-height:30px;height:30px;padding-left:10px;}#swtm div.msgbox_close {background:url(../images/msgbox/close.gif) no-repeat;width:10px;margin-right:30px;margin-top:10px;height:10px;float:right;cursor:pointer;}#swtm div span {color:#FCFF00;}#swtm div.msgbox_context {margin-left:118px;width:240px;}#swtm p#msgbox_text {padding:8px;width:240px;height:32px;line-height:20px;overflow:hidden;text-indent:2em;font-size:12px;color:#555555;}#swtm ul#msgbox_hot {font-size:12px;line-height:20px;height:40px;list-style:none;margin:0;margin-left:20px;padding:5px;padding-bottom:8px;}#swtm ul#msgbox_hot li {height:20px;line-height:20px;}#swtm ul#msgbox_hot li a {font-family:Arial,宋体;font-size:12px;color:#FF0065;text-decoration:none;}#swtm ul#msgbox_hot li a:hover {text-decoration:underline;}#swtm div.msgbox_button {margin-left:42px;margin-top:3px;height:24px;}#swtm div.msgbox_button a {margin-right:11px;}#swtm div#msgbox_prompt {height:18px;line-height:18px;margin-left:90px;margin-top:10px;color:#353535;overflow:hidden;}");
add_css("#swtf {background:url(../images/bf.jpg) no-repeat;width:419px;height:224px;position:absolute;z-index:999;right:5px;font-family:Arial,宋体;font-size:12px;}#swtf div.msgbox_title {font-size:14px;font-weight:bold;color:White;font-family:Arial,宋体;float:left;line-height:30px;height:30px;padding-left:10px;}#swtf div.msgbox_close {background:url(../images/msgbox/close.gif) no-repeat;width:10px;margin-right:30px;margin-top:10px;height:10px;float:right;cursor:pointer;}#swtf div span {color:#FCFF00;}#swtf div.msgbox_context {margin-left:118px;width:240px;}#swtf div#msgbox_text {padding:10px;padding-bottom:0px;width:240px;height:40px;line-height:20px;overflow:hidden;text-indent:2em;font-size:12px;color:#555555;}#swtf ul#msgbox_tel {font-size:12px;line-height:24px;height:40px;list-style:none;margin:0;padding:5px;margin-left:100px;}#swtf ul#msgbox_tel li {font-size:14px;font-weight:bold;color:#277308;}#swtf div.msgbox_button {margin-left:40px;margin-top:14px;height:24px;}#swtf div.msgbox_button a {margin-right:11px;}#swtf ul#msgbox_hot {height:18px;line-height:18px;margin-left:80px;margin-top:17px;color:#353535;}#swtf ul#msgbox_hot li {width:120px;overflow:hidden;height:20px;float:left;margin-right:20px;}#swtf ul#msgbox_hot a {font-family:Arial,宋体;font-size:12px;color:Black;text-decoration:none;}#swtf ul#msgbox_hot a:hover {text-decoration:underline;}");
var swtm = "<div id=\"swtm\"><div class=\"msgbox_title\">您好,这里是<span id=\"msgbox_titles\">中华人民共和国</span></div><div class=\"msgbox_close\" onclick=\"$('swtm').parentNode.removeChild($('swtm'));\"></div><div class=\"msgbox_context\"><p id=\"msgbox_text\">中华人民共和国中华人民共和国中华人民共和国中华人民共和国中华人民共和国中华人民共和国中华人民共和国</p><ul id=\"msgbox_hot\"><li><a href='#'>中华人民共和国</a></li><li><a href='#'>中华人民共和国</a></li></ul><div class=\"msgbox_button\"><a id=\"actions\" href=\"#\" target=\"_blank\"><img src=\"<%=WebSiteUrl%>/images/msgbox/btn1.gif\" width=\"88\" height=\"24\" border=\"0\" alt=\"\" /></a><a href=\"javascript:void(0);\" onclick=\"$('swtm').parentNode.removeChild($('swtm'));\"><img src=\"<%=WebSiteUrl%>/images/msgbox/btn2.gif\" width=\"88\" height=\"24\" border=\"0\" alt=\"\" /></a></div></div><div id=\"msgbox_prompt\">中华人民共和国中华人民共和国</div></div>";
var swtf = "<div id=\"swtf\"><div class=\"msgbox_title\">您好,这里是<span id=\"msgbox_titles\">中华人民共和国</span></div><div class=\"msgbox_close\" onclick=\"$('swtf').parentNode.removeChild($('swtf'));\"></div><div class=\"msgbox_context\"><div id=\"msgbox_text\">中华人民共和国中华人民共和国中华人民共和国中华人民共和国中华人民共和国中华人民共和国中华人民共和国</div><ul id=\"msgbox_tel\"><li id=\"msgbox_tel1\">0755-88888888</li><li id=\"msgbox_tel2\">0755-88888888</li></ul><div class=\"msgbox_button\"><a id=\"actions\" href=\"#\" target=\"_blank\"><img src=\"<%=WebSiteUrl%>/images/msgbox/btn1.gif\" width=\"88\" height=\"24\" border=\"0\" alt=\"\" /></a><a href=\"javascript:void(0);\" onclick=\"$('swtf').parentNode.removeChild($('swtf'));\"><img src=\"<%=WebSiteUrl%>/images/msgbox/btn2.gif\" width=\"88\" height=\"24\" border=\"0\" alt=\"\" /></a></div></div><ul id=\"msgbox_hot\"><li><a href='#'>中华人民共和国中华人民共和国</a></li><li><a href='#'>中华人民共和国中华人民共和国</a></li></ul></div>";
var div = document.createElement("div");
div.innerHTML = swtf;
document.body.insertBefore(div, document.body.childNodes[0]);
var msgboxsHeight = $(objid).offsetHeight;
scrollHandler();
</script>
</body>
</html>
